// <auto-generated />
namespace MMSdb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addingtbl_ReportRightsUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingtbl_ReportRightsUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202009221239313_addingtbl_ReportRightsUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
